"""
select.py — CBSE blueprint selection from questionsitoviii.db.

Reads a class/subject + blueprint (per-section counts, optional chapter/difficulty
filters) and produces a cbse_paper_content.json the PDF/DOCX builders consume.
Carries the canonical LaTeX (question_latex / *_latex) through untouched.

questionsitoviii.db is opened READ-ONLY (it may be regenerated by the ingestion
pipeline); no usage/history is written here.
"""
from __future__ import annotations

import random

from engine import db as _db  # reuse the read-only sqlite opener
from . import blueprint as _bp

LETTERS = ["a", "b", "c", "d", "e", "f"]


# ------------------------------------------------------------------ filters
def _where(book_id, chapter_ids, difficulties, alias="q"):
    where = [f"{alias}.chapter_id IN (SELECT id FROM chapters WHERE book_id=?)"]
    params = [book_id]
    if chapter_ids:
        where.append(f"{alias}.chapter_id IN ({','.join('?' for _ in chapter_ids)})")
        params += list(chapter_ids)
    if difficulties:
        where.append(f"{alias}.difficulty IN ({','.join('?' for _ in difficulties)})")
        params += list(difficulties)
    return " AND ".join(where), params


# ------------------------------------------------------------------ metadata
def book_for_class(con, class_number, subject=None):
    q = "SELECT * FROM books WHERE class_number=?"
    p = [class_number]
    if subject:
        q += " AND subject=?"
        p.append(subject)
    return _db.one(con, q + " LIMIT 1", p)


def chapters_for_book(con, book_id):
    return _db.dicts(con, "SELECT id, name, chapter_number FROM chapters WHERE book_id=? ORDER BY chapter_number", (book_id,))


# ------------------------------------------------------------------ fetch
def _candidate_ids(con, book_id, types, chapter_ids, difficulties):
    base, params = _where(book_id, chapter_ids, difficulties)
    ph = ",".join("?" for _ in types)
    rows = _db.dicts(
        con,
        f"SELECT q.id, q.question_number, q.context_block_id FROM questions q "
        f"WHERE {base} AND q.type IN ({ph})",
        params + list(types),
    )
    return rows


def fetch_full_question(con, qid):
    q = _db.one(con, "SELECT * FROM questions WHERE id=?", (qid,))
    opts = _db.dicts(con, "SELECT label, text, text_latex, image FROM options WHERE question_id=? ORDER BY label", (qid,))
    # relabel options a,b,c,d… and remap the correct answer to the new label
    orig_correct = (q.get("correct_answer_latex") or q.get("correct_answer") or "").strip().lower()
    new_correct = None
    for i, opt in enumerate(opts):
        orig = (opt.get("label") or "").strip().lower()
        new = LETTERS[i] if i < len(LETTERS) else opt["label"]
        if orig and orig == orig_correct:
            new_correct = new
        opt["label"] = new
    q["options"] = opts
    if new_correct:
        q["correct_answer_display"] = new_correct
    else:
        q["correct_answer_display"] = q.get("correct_answer_latex") or q.get("correct_answer")
    return q


def _rank(rows, mode, rng):
    if mode == "sequential":
        return sorted(rows, key=lambda r: (r.get("question_number") or 0, r["id"]))
    ordered = rows[:]
    rng.shuffle(ordered)
    return ordered


# ------------------------------------------------------------------ main
def select_paper(con, cfg):
    rng = random.Random(cfg.get("random_seed"))
    mode = cfg.get("selection_mode", "random")
    warnings = []

    class_number = cfg["class_number"]
    subject = cfg.get("subject")
    book = book_for_class(con, class_number, subject)
    if not book:
        raise ValueError(f"no book found for class {class_number}" + (f" / {subject}" if subject else ""))

    chapter_ids = [int(x) for x in (cfg.get("chapters") or [])]
    difficulties = list(cfg.get("difficulty") or [])

    sections_out = []
    blocks = {}

    for sec in _bp.resolve_sections(cfg):
        rows = _candidate_ids(con, book["id"], sec["draw_types"], chapter_ids, difficulties)

        chosen_qs = []
        if sec["intact_blocks"]:
            # case-based: pick whole context_blocks (cases), keep sub-questions together
            by_block = {}
            for r in rows:
                cb = r.get("context_block_id")
                if cb is None:
                    continue
                by_block.setdefault(cb, []).append(r)
            block_ids = _rank([{"id": b, "question_number": min(x["question_number"] or 0 for x in v)}
                               for b, v in by_block.items()], mode, rng)
            for b in block_ids[: sec["count"]]:
                cb_id = b["id"]
                cb = _db.one(con, "SELECT * FROM context_blocks WHERE id=?", (cb_id,))
                if cb:
                    blocks[str(cb_id)] = {k: cb.get(k) for k in ("id", "type", "category", "text", "text_latex", "image")}
                for r in sorted(by_block[cb_id], key=lambda x: (x["question_number"] or 0, x["id"])):
                    chosen_qs.append(r["id"])
            got_units = min(len(block_ids), sec["count"])
            if got_units < sec["count"]:
                warnings.append(f"Section {sec['code']}: wanted {sec['count']} case blocks, only {got_units} available.")
        else:
            ranked = _rank(rows, mode, rng)
            chosen_qs = [r["id"] for r in ranked[: sec["count"]]]
            if len(chosen_qs) < sec["count"]:
                warnings.append(f"Section {sec['code']}: wanted {sec['count']}, only {len(chosen_qs)} available.")

        questions = []
        for qid in chosen_qs:
            q = fetch_full_question(con, qid)
            q["section_marks"] = sec["marks_per"]  # standardized per section
            questions.append(q)

        sections_out.append({
            "code": sec["code"], "title": sec["title"], "instruction": sec["instruction"],
            "marks_per": sec["marks_per"], "intact_blocks": sec["intact_blocks"],
            "questions": questions,
        })

    # display numbering: continuous across the whole paper
    n = 1
    for sec in sections_out:
        for q in sec["questions"]:
            q["display_number"] = n
            n += 1

    max_marks = sum(len(sec["questions"]) * sec["marks_per"] for sec in sections_out
                    if not sec["intact_blocks"]) + \
                sum(sec["marks_per"] * _count_case_blocks(sec) for sec in sections_out if sec["intact_blocks"])

    return {
        "exam_type": "cbse",
        "paper_title": cfg.get("paper_title", f"{book.get('subject','')} — Class {book.get('class_level','')}"),
        "class_label": book.get("class_level"),
        "class_number": class_number,
        "subject": book.get("subject"),
        "book_title": book.get("title"),
        "exam_duration": cfg.get("exam_duration", "3 Hours"),
        "max_marks": round(max_marks, 1),
        "sections": sections_out,
        "context_blocks": blocks,
        "warnings": warnings,
    }


def _count_case_blocks(sec):
    return len({q.get("context_block_id") for q in sec["questions"] if q.get("context_block_id")})
