"""
Loads the correct-answer key from an Excel file.

Expected format (see sample_answer_key.xlsx generated by
tools/generate_sample_key.py): a sheet named "AnswerKey" with a
"Question" (1-100) column, an "Answer" column, and four optional
columns - "Marks", "Negative Marks", "Is Bonus", "Is Multi Correct" -
that override the batch-wide defaults in config.json's marking_scheme
on a per-question basis. Question numbers may be in any order.

ANSWER COLUMN SYNTAX
---------------------
A question can be correct in more than one way, and the "Is Multi
Correct" column decides how multiple letters in the Answer cell are
read:

  - "Is Multi Correct" = 0 (or the column is present but blank/absent
    for this row): the letters are alternatives - the student only
    needs to shade ONE of them. "B C" or "BC" here means "B or C is
    each independently acceptable as the single correct answer" (the
    "any one best response" case).
  - "Is Multi Correct" = 1: the letters must ALL be shaded together to
    count as correct - "B C" means the student must shade exactly B
    AND C (matching this project's original multi-answer behavior).
  - If the "Is Multi Correct" column doesn't exist in the sheet at
    all (an older key file), multi-letter cells default to the AND
    reading above, so existing key files keep scoring exactly as
    before without any changes.

For anything more complex than "all of these together" or "any one of
these", write the logic explicitly with "and"/"or" right in the Answer
cell - this always overrides the Is Multi Correct column, since it's
unambiguous either way:

  - "A and B"             - both A and B must be shaded together
  - "C or D"               - either C alone or D alone is accepted
  - "A and B or C and D"   - exactly {A,B} is accepted, and separately
                             exactly {C,D} is also accepted (but not
                             e.g. {A,B,C} or {A} alone)

PER-QUESTION MARKS / NEGATIVE MARKS
-------------------------------------
"Marks" is how many marks a correct (or bonus) answer to that question
is worth; "Negative Marks" is how many marks are DEDUCTED for a wrong
answer (a positive number - e.g. 0.25 means -0.25, not +0.25). Leave
either blank to fall back to config.json's marking_scheme.correct /
abs(marking_scheme.wrong) for that question.

BONUS QUESTIONS
----------------
"Is Bonus" = 1 marks a question as correct for EVERY student
automatically, regardless of what (if anything) they shaded - full
marks awarded, no penalty possible. Used for questions later found to
be flawed/unanswerable, where the fair fix is to give everyone credit
rather than rescore.

The OMR sheet always has 100 printed bubbles, but a given exam may use
fewer than 100 questions. To support that, only the HIGHEST keyed
question number is treated as "the last real question" - any rows
after that with no answer are treated as "this exam doesn't have that
many questions" and silently excluded everywhere downstream (not
scored, not shown in reports), rather than being flagged as missing.
Gaps BEFORE the highest keyed question (e.g. Q1-80 filled but Q50
missing) are still treated as a likely mistake and reported as a
warning, since those look like an oversight rather than "the exam
stops here".
"""

import re

import openpyxl

VALID_OPTIONS = {"A", "B", "C", "D"}

TRUE_VALUES = {"1", "y", "yes", "true", "t"}
FALSE_VALUES = {"0", "n", "no", "false", "f", ""}


def _to_bool(val, default=False):
    if val is None:
        return default
    text = str(val).strip().lower()
    if text in TRUE_VALUES:
        return True
    if text in FALSE_VALUES:
        return default
    try:
        return float(text) != 0
    except ValueError:
        return default


def _to_float(val, default):
    if val is None or str(val).strip() == "":
        return default
    try:
        return float(val)
    except (TypeError, ValueError):
        return default


def _extract_letters(text):
    return tuple(sorted({ch.upper() for ch in re.findall(r"[A-Da-d]", text)} & VALID_OPTIONS))


def parse_answer_expression(raw_text, is_multi_correct):
    """Parses an Answer cell into a list of "clauses" - a DNF (OR-of-ANDs)
    representation. Each clause is a sorted tuple of letters that must
    be shaded EXACTLY (no more, no fewer) for the question to count as
    correct; the whole question is correct if the student's shaded set
    exactly matches ANY one clause. Returns None if the cell has no
    usable answer at all.

    See the module docstring for the "and"/"or" syntax and the
    `is_multi_correct` fallback behavior for plain letter lists.
    """
    if raw_text is None:
        return None
    text = str(raw_text).strip()
    if not text:
        return None

    has_logic_keyword = re.search(r"\b(and|or)\b", text, re.IGNORECASE) is not None
    if has_logic_keyword:
        or_parts = re.split(r"\bor\b", text, flags=re.IGNORECASE)
        clauses = []
        for part in or_parts:
            and_parts = re.split(r"\band\b", part, flags=re.IGNORECASE)
            letters = []
            for term in and_parts:
                letters.extend(re.findall(r"[A-Da-d]", term))
            clause = tuple(sorted({ch.upper() for ch in letters} & VALID_OPTIONS))
            if clause:
                clauses.append(clause)
        return clauses or None

    letters = _extract_letters(text)
    if not letters:
        return None
    if len(letters) == 1:
        return [letters]
    if is_multi_correct:
        return [letters]                  # AND: all must be shaded together
    return [(letter,) for letter in letters]  # OR: any one of these alone is accepted


def format_clauses(clauses):
    """Human-readable rendering of a parsed answer, for reports/PDFs -
    e.g. [("C",)] -> "C", [("A",),("B",)] -> "A or B", [("A","B")] ->
    "A and B", [("A","B"),("C","D")] -> "A and B or C and D"."""
    if not clauses:
        return "-"
    parts = []
    for clause in clauses:
        parts.append(" and ".join(clause))
    return " or ".join(parts)


def load_answer_key(path, sheet_name="AnswerKey", num_questions=100, marking_scheme=None):
    marking_scheme = marking_scheme or {}
    default_marks = marking_scheme.get("correct", 1.0)
    default_negative_marks = abs(marking_scheme.get("wrong", 0.0))

    wb = openpyxl.load_workbook(path, data_only=True)
    if sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
    else:
        ws = wb.active  # fall back to first sheet

    header = [str(c.value).strip().lower() if c.value else "" for c in ws[1]]
    try:
        q_col = header.index("question")
        a_col = header.index("answer")
    except ValueError:
        raise ValueError(
            "Answer key must have 'Question' and 'Answer' column headers in row 1"
        )
    marks_col = header.index("marks") if "marks" in header else None
    neg_col = header.index("negative marks") if "negative marks" in header else None
    bonus_col = header.index("is bonus") if "is bonus" in header else None
    multi_col = header.index("is multi correct") if "is multi correct" in header else None

    key = {}
    warnings = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        q_val, a_val = row[q_col], row[a_col]
        if q_val is None:
            continue
        try:
            q_num = int(q_val)
        except (TypeError, ValueError):
            warnings.append(f"Skipped row with non-numeric question '{q_val}'")
            continue
        if not (1 <= q_num <= num_questions):
            continue

        is_bonus = _to_bool(row[bonus_col]) if bonus_col is not None and bonus_col < len(row) else False
        # If the column exists at all, an explicit value drives parsing;
        # if it's entirely absent (older key file), default to the old
        # AND behavior so existing key files don't silently rescore.
        if multi_col is not None and multi_col < len(row):
            is_multi_correct = _to_bool(row[multi_col], default=False)
        else:
            is_multi_correct = True

        clauses = parse_answer_expression(a_val, is_multi_correct)
        if not clauses and not is_bonus:
            continue  # no answer given for this row - handled below via the gap check

        marks = _to_float(row[marks_col] if marks_col is not None and marks_col < len(row) else None, default_marks)
        negative_marks = _to_float(
            row[neg_col] if neg_col is not None and neg_col < len(row) else None, default_negative_marks
        )

        key[q_num] = {
            "clauses": clauses or [],
            "marks": marks,
            "negative_marks": negative_marks,
            "is_bonus": is_bonus,
            "is_multi_correct": is_multi_correct,
        }

    if key:
        last_real_question = max(key.keys())
        # Gaps at or before the last keyed question look like a genuine
        # oversight; gaps after it just mean the exam has fewer than
        # `num_questions` questions - expected, not a warning.
        missing = sorted(set(range(1, last_real_question + 1)) - set(key.keys()))
        if missing:
            warnings.append(f"No valid answer provided for questions: {missing}")
        if last_real_question < num_questions:
            warnings.append(
                f"Answer key only has {last_real_question} question(s) - "
                f"questions {last_real_question + 1}-{num_questions} will be "
                f"excluded from scoring and reports entirely."
            )
    else:
        warnings.append("Answer key has no valid answers for any question.")

    return key, warnings
